# ========================
# Application
# ========================
spring.application.name=order
server.port= 3200

# ========================
# PostgreSQL
# ========================
spring.datasource.url=jdbc:postgresql://localhost:5432/portfolioServiceDb
spring.datasource.username=testeur
spring.datasource.password=testeur

# ========================
# spring boot actuator
# ========================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.server.port=3201


# ========================
# Swagger
# ========================
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/api-docs

# ========================
# migration
# ========================
spring.jpa.hibernate.ddl-auto=update


# ========================
# JwtService
# ========================
jwt.secret=je-suis-sence-ecrire-une-bonne-cle-secrete-dau-moin-32-caracteres 



# ========================
# spring security logs
# ========================
logging.level.org.springframework.security=TRACE